### ISSUE TITLE
Some suggestion I'd love to see

### ISSUE THREAD

**Issue by TierraVulture** [EterDelta/CrittersAndCompanions#12]
I'd love for leaf insects to be tameable as many people irl keep them as pets! I'd also love to see more types of arthropods like jumping spiders or rhinoceros beetles. 

- Also I have a question, are there any plans for the mobs that currently don't have any function to get some in the future?

**Comment by EterDelta** [comment]
As far as I know, we have no current plans to add tameable leaf insects. Still, **version 1.1.0** introduces many new behaviors and functions for the current mobs!
I'll close this for now.
