### ISSUE TITLE
Sea Bunnies spawning in Mob Farms

### ISSUE THREAD

**Issue by VeggeieDude** [EterDelta/CrittersAndCompanions#15]
Heya! My friend made a mod farm over the ocean, and noticed sea bunnies spawn in it a lot.

The farm is in the air and releases water every now and then to push mobs into the middle where they'll drop into the middle and fall into a hopper trap.

The sea bunnies spawn in the water source blocks.

Was wondering if you wouldn't mind changing the spawn height of Sea Bunnies to sea level or below so they won't spawn in midair farms above oceans.

We're using forge version 1.18.2, thank you!

**Comment by EterDelta** [comment]
Thanks for the report, this was fixed in version **1.1.2**.
