### ISSUE TITLE
Can't Tame Dragonflies & Ferrets Won't Dig [1.0.3 for Fabric]

### ISSUE THREAD

**Issue by SinsOfVirtue** [EterDelta/CrittersAndCompanions#17]
Hi there,

I've tamed a ferret and feeding it raw chicken doesn't get it to dig at any point. And my friend on his own file is trying to tame a dragonfly with a spider eye but hasn't been able to. We're both running the latest version , 1.0.3, on Fabric 0.14.10 for 1.19.2.

**Comment by EterDelta** [comment]
Sorry, but tameable dragonflies and ferret digging are **1.1** exclusive features.
Fabric port is still on **1.0** and we have no ETA for the new version.
