### ISSUE TITLE
Crash while ticking entity

### ISSUE THREAD

**Issue by itsNordLord** [EterDelta/CrittersAndCompanions#19]
**Issue:**
Minecraft is crashing with Critters and Companions installed. The log is suggesting that Ferrets are causing the crash. Crash report here: https://paste.gg/p/anonymous/fe356861846d4a72b812161676236fbd

I am able to reproduce this issue

**Dependencies:** 
Minecraft: 1.19.2
Fabric Loader: 0.14.13
Fabric API: 0.73.2
Critters & Companions: 1.0.3
Geckolib: 3.1.38

**Comment by EterDelta** [comment]
Thanks for the report!
This is the Forge repo, please move this issue to the Fabric repo, which is mantained by someone else:
https://github.com/LLytho/CrittersAndCompanions-Fabric/tree/1.19.2

Sorry for the inconvenience.
