### ISSUE TITLE
No config?

### ISSUE THREAD

**Issue by IdrisQe** [EterDelta/CrittersAndCompanions#2]
I put v1.0.0 in my 1.18.2 Forge instance and started the game. I then entered a world, exited the world, and quit the game. Upon going to the configs folder and the serverconfigs folder, I can't seem to find anything related to this mod? Is there no config implemented yet, or is this some kind of bug, or am I just missing the config because it has a strange name?

**Comment by EterDelta** [comment]
Currently, there are no plans on adding a config for the mod. 
No file exists.

**Comment by IdrisQe** [comment]
A... mob mod... with no config?

So every end-user has to make an entire datapack if they want to alter mob spawns or anything?...

Hm... Aaaaaalright then.

**Comment by EterDelta** [comment]
Feel free to make a PR and add a configuration whenever you want.
Priorities exist, and as I said, _at the moment_ there are more important things we are focusing on fixing.

**Comment by EterDelta** [comment]
Since Minecraft version **1.19**, Forge introduced a new system to control mob spawns through datapacks. Doing it from config files is no longer possible and this should be the preferred way.
