### ISSUE TITLE
[1.19.2][FORGE] Dumbo Octopus disappearing from pond.

### ISSUE THREAD

**Issue by Kdschar** [EterDelta/CrittersAndCompanions#26]
Not sure if I've done something wrong or if it's just a fluke, but my dumbo octopus I put in a pond by my house has disappeared twice now. It could have died while I was away I suppose, I'm just not sure how. Are there any requirements for them to stay alive? A certain water depth maybe? I didn't have any luck finding a wiki. Thanks!

**Comment by EterDelta** [comment]
Fixed in 2.0.1
