### ISSUE TITLE
CarryOn compatibility 

### ISSUE THREAD

**Issue by SucksAtstuff** [EterDelta/CrittersAndCompanions#3]
so if you pickup the otter and go in f5 you crash or if you're playing multiplayer if you pick it up in front of people you crash i dont know if it does the same for the other mobs

**Comment by SucksAtstuff** [comment]
so its any animal from the mod that crashes when you try to pick it up

**Comment by EterDelta** [comment]
Not caused by Critters and Companions.
This issue is fixed in the latest GeckoLib version. https://github.com/bernie-g/geckolib/pull/280
