### ISSUE TITLE
1.20.1 port

### ISSUE THREAD

**Issue by gohkenytp** [EterDelta/CrittersAndCompanions#44]
Would you kindly port this mod to Forge 1.20.1 please? Thank you.

**Comment by poly2it** [comment]
And fabric.

**Comment by PeakXing** [comment]
Please update Fabric 1.20.1! Tky

**Comment by acanthii** [comment]
[crittersandcompanions-fabric-1.20.1-2.0.3.zip](https://github.com/bonsaistudi0s/CrittersAndCompanions/files/13760883/crittersandcompanions-fabric-1.20.1-2.0.3.zip) (unzip and put the .jar file in your mods folder)

Temporary **Unofficial** Fabric 1.20.1, pls **don't report bugs** to this github page bc it's **not an official build** of Critters and Companions and **both you and I will both be ridiculed for it.**
Known Issues:
\- Otters don't show what they are holding
\- ~~Ferrets have an... interesting idle pose.~~
\- ~~Creative Tab only shows clams (you can use REI/EMI(with 'registered' option, or use /give)~~
\- Doesn't contain anything that wasn't in the 1.19 fabric version (meaning no Jumping Spiders, no Sea Slug Slime Blocks, etc)

**Requires Geckolib 4.3.1, will crash if you don't have it installed.**

**Comment by acanthii** [comment]
[crittersandcompanions-fabric-1.20.1-2.0.3.zip](https://github.com/bonsaistudi0s/CrittersAndCompanions/files/13760975/crittersandcompanions-fabric-1.20.1-2.0.3.zip) (Version 2) (unzip and put the .jar file in your mods folder)

Temporary **Unofficial** Fabric 1.20.1, pls **don't report bugs** to this github page bc it's **not an official build** of Critters and Companions and **both you and I will both be ridiculed for it.**
Fixed from previous version:
\+ Ferret default pose
\+ Creative Tab

**Requires Geckolib 4.3.1, will crash if you don't have it installed.**

**Comment by smifflepuss** [comment]
Do you have a unofficial port for Forge?

**Comment by acanthii** [comment]
I'm sort of a beginner and fabric is the platform I know best, though I'll try and see how much of the code is convertible between platforms.
I only posted the fabric version because I made it for my own modpack and didn't just wanna keep it exclusive to myself haha (felt wrong)
Sorry to disappoint

**Comment by EterDelta** [comment]
@snoandpetals I would recommend doing a PR with the port in the [Fabric repo](https://github.com/LLytho/CrittersAndCompanions-Fabric).
Endorsing people to use unofficial, closed builds is dangerous. Besides, by contributing the code you help a lot :)

**Comment by acanthii** [comment]
Didn't know the devs saw it that way, sorry, I'll upload my source code immediately ^-^

**Comment by acanthii** [comment]
@EterDelta 
I can't exactly make a PR because LLytho doesn't have a 1.20.1 branch but code is here :3
https://github.com/snoandpetals/CrittersAndCompanions-Fabric (under branch 1.20.1)

It does make a few changes from the base mod like adding a sitting 'animation' to the Shima Enaga, and having the pearl necklace just be named "Pearl Necklace" (because the level is in the tooltip) but nothing 'dangerous' as far as I know, if you do find something that would cause crashes or something lmk and i'll fix it asap

**Comment by acanthii** [comment]
Actually I probably could just make a PR from my 1.20.1 branch to their 1.19.2 branch and they could duplicate their 1.19.2 branch before accepting my PR
Alright, I'll submit the PR :3

EDIT: pr made :)
https://github.com/LLytho/CrittersAndCompanions-Fabric/pull/4

EDIT 2: PR was denied

**Comment by soleilan** [comment]
Apologize for pestering but an update to 1.20.1 would be lovely

**Comment by CodexAdrian** [comment]
Critters and Companions is now released for 1.20.1
