### ISSUE TITLE
Crash with forge 1.19.2 on the latest update (2.1.0)

### ISSUE THREAD

**Issue by norfaremc** [EterDelta/CrittersAndCompanions#50]
We updated our modlist and server to include the latest patch for Critters and Companions , and we're now experiencing this crash in the world:
[crash-2023-12-11_05.30.32-server.txt](https://github.com/bonsaistudi0s/CrittersAndCompanions/files/13632213/crash-2023-12-11_05.30.32-server.txt)
It appears to be a zombie, but it somehow involves the silk leash item? Any ideas? Right now our server is pretty unplayable due to this recurring so often.

**Comment by Blakesan** [comment]
Running updates today & we started receiving lots of the same crash as stated above. Had to roll back in order to get stability.
Zombie entity and silk leash seem to be clashing in some strange way. 

[crash-2023-12-12_13.57.46-server.txt](https://github.com/bonsaistudi0s/CrittersAndCompanions/files/13653275/crash-2023-12-12_13.57.46-server.txt)

**Comment by 5stigma** [comment]
Im crash with DragonSurvival.
[crash-2023-12-12_18.37.10-client.txt](https://github.com/bonsaistudi0s/CrittersAndCompanions/files/13655116/crash-2023-12-12_18.37.10-client.txt)

**Comment by rommyrom334** [comment]
it's because it's an issue with the a.i. of the new jumping spider. i don't know if he forgot to add it in or something went wrong with the process of it

**Comment by EterDelta** [comment]
> it's because it's an issue with the a.i. of the new jumping spider. i don't know if he forgot to add it in or something went wrong with the process of it

This has nothing to do. The problem was already identified and should be fixed in **2.1.1** when it gets uploaded to CF.
Thanks everyone for the reports!

**Comment by EterDelta** [comment]
Fixed in **2.1.1**.
@norfaremc Your case was a bit different, so if the problem still persists, please open a new issue.
