### ISSUE TITLE
Quilt/Fabric update for 1.20.1?

### ISSUE THREAD

**Issue by SafTheLamb** [EterDelta/CrittersAndCompanions#52]
Hi! I really want to use this mod, but I've set up my mods with 1.20.1 since that's what's most commonly supported currently (and Quilt doesn't have a port for 1.20.2+ yet anyway). Could you update the mod to support 1.20.1? I tested the quick-fix submitted by another user but that crashed on launch.

Thanks and cheers! Such an adorable and curated selection of creatures to add :)

**Comment by acanthii** [comment]
Dev of the quick fix here, just to be sure, did you install Geckolib 4.3.1 or above for 1.20.1? I think I asked people to download it in the OG thread but I should've listed it as a requirement in the fabric.mod.json tbf

EDIT: if that still doesn't work drop a crash log here so I can analyse it :3

**Comment by SafTheLamb** [comment]
Hi! I missed that, with geckolib included it works great, thank you! I'd just assumed it was a conflict with one of the other mods I had installed.
