### ISSUE TITLE
Minecolonies Incompatability 1.19.2

### ISSUE THREAD

**Issue by Mimic0445** [EterDelta/CrittersAndCompanions#53]
Silk Lead causes a crash when rendering a Minecolonies raid ship.

See Minecolonies 
https://github.com/ldtteam/minecolonies/issues/9640

[Crash Report](https://gist.github.com/Mimic0445/620f6238ce3357317a6667759b44dd3c)

**Comment by EterDelta** [comment]
You are using version an outdated version of the mod.
This is a known problem, and has already been resolved in 2.1.1. Closing as resolved.
