### ISSUE TITLE
Crash server 1.20.1

### ISSUE THREAD

**Issue by Davokushi** [EterDelta/CrittersAndCompanions#60]
No crash Client only Server
If you require more information, let me know.

[crash-2024-04-28_12.37.57-fml.txt](https://github.com/bonsaistudi0s/CrittersAndCompanions/files/15143039/crash-2024-04-28_12.37.57-fml.txt)

**Comment by Lilyp3892** [comment]
a working one can be found here https://github.com/bonsaistudi0s/CrittersAndCompanions/files/14501722/crittersandcompanions-1.20.1-2.1.1.zip

(from: https://github.com/bonsaistudi0s/CrittersAndCompanions/pull/59#issuecomment-1979676523)

**Comment by EarthboundRune** [comment]
playing a 1.20.1 sever and I love this mod but it does crash on severs... Does the one linked about actually work? I want this mod but I don't want to fry my sever...

**Comment by Davokushi** [comment]
> a working one can be found here https://github.com/bonsaistudi0s/CrittersAndCompanions/files/14501722/crittersandcompanions-1.20.1-2.1.1.zip
> 
> (from: [#59 (comment)](https://github.com/bonsaistudi0s/CrittersAndCompanions/pull/59#issuecomment-1979676523))

It's official?
I'm going to try it

**Comment by Handrail9** [comment]
> > a working one can be found here https://github.com/bonsaistudi0s/CrittersAndCompanions/files/14501722/crittersandcompanions-1.20.1-2.1.1.zip
> > (from: [#59 (comment)](https://github.com/bonsaistudi0s/CrittersAndCompanions/pull/59#issuecomment-1979676523))
> 
> It's official? I'm going to try it

It's from a contributor to the project but it isn't a main release. Regardless that build does not seem to fix the issue (I just tried testing it)

**Comment by CodexAdrian** [comment]
Fixed in 2.1.3. Also please do not download unofficial builds
