### ISSUE TITLE
Quilt (/Fabric) support for 1.20.1?

### ISSUE THREAD

**Issue by SafTheLamb** [EterDelta/CrittersAndCompanions#65]
Hiya!

I was wondering if a port to quilt/fabric for 1.20.x (specifically 1.20.1 is what I'm using) is planned?

Thanks!
SafTheLamb

**Comment by csm-kb** [comment]
@CodexAdrian hey, how far behind is the `1.20.1-xplat` branch from `1.20.1`? Was the goal there to migrate the mod to the cross-platform build setup (e.g. like geckolib's source)? Very interested in helping with that (hopefully bringing in #59 ), unless you have plans to tackle this!

**Comment by Tyrasuki** [comment]
Would love to see this happen!
Unfortunately I have not touched Java in years, so I don't believe I can be of much assistance.

**Comment by MJRamon** [comment]
Damn, still no 1.20.1 support for Fabric?

**Comment by Mortycio** [comment]
Up 🆙🙏

**Comment by PssbleTrngle** [comment]
fabric for 1.20.1 is here
