### ISSUE TITLE
Critters and Companions 1.20.1 wont run under GeckoLib fabric Sinytra Connector

### ISSUE THREAD

**Issue by FullMetalMaster** [EterDelta/CrittersAndCompanions#77]
trying to run this mod under fabric version will break all texts and crash the game.

most other mods are compatible not sure why this one isn't is there a fabric version coming soon?

**Comment by PssbleTrngle** [comment]
a fabric version is here 🥳

**Comment by FullMetalMaster** [comment]
lets go!
