### ISSUE TITLE
Crash Related to Critters and Companions (Version 1.20.1-2.1.7)

### ISSUE THREAD

**Issue by ThunderWeed** [EterDelta/CrittersAndCompanions#78]
Hello,

I hope you're doing well. I am currently running a Minecraft server (version 1.20.1) with the Critters and Companions mod (version 1.20.1-2.1.7) installed, but I’ve encountered an issue that causes my server to crash. The problem seems to be linked to the mixin class in your mod.

Here is the relevant portion of the crash report:

`Thread: Server thread
Suspected Mod: 
   Critters and Companions (crittersandcompanions), Version: 1.20.1-2.1.7
   Mixin class: com.github.eterdelta.crittersandcompanions.mixin.LivingEntityMixin
   Target: net.minecraft.world.entity.LivingEntity
   at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.entity.LivingEntity.handler$zof002$onTick(LivingEntity.java:10628)
`

It seems that the error happens when the server tries to tick a LivingEntity (in this case, a zombie), and it results in a crash. This is the full stack trace that mentions the issue with your mixin class.

Would you kindly look into this and see if there’s a potential fix or workaround? I’d appreciate any assistance you could provide in resolving this problem.

If you need more information or the complete crash report, feel free to let me know!

Thank you for your time and for your work on the mod!

**Comment by ThunderWeed** [comment]
Сomplete crash report:
https://mclo.gs/S3SMZRY

**Comment by Nero-Lokin** [comment]
I am having a similar crash. It is the same mixin for me as well.

**Comment by PssbleTrngle** [comment]
Should be fixed in >=2.2.0, if not feel free to reopen
