### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by MisterAndyDandy** [EterDelta/CrittersAndCompanions#8]
Just running around world and sometimes I will crash out right it's something to do with your mod. 

[crash-2022-10-26_23.06.13-client.txt](https://github.com/bonsaistudi0s/CrittersAndCompanions/files/9874056/crash-2022-10-26_23.06.13-client.txt)

I am using the lately one from your mod but think it because I am using a newer geckolib-forge-1.18-3.0.48.jar

**Comment by EterDelta** [comment]
This seems to be a GeckoLib issue. I tested with the **latest** library version and got no errors regarding that report.
If you still get the crash please give more information and steps to reproduce it.
