### ISSUE TITLE
Dedicated server crashes on 2.2.0

### ISSUE THREAD

**Issue by FemBane** [EterDelta/CrittersAndCompanions#84]
Run on my [modpack](https://www.curseforge.com/minecraft/modpacks/dimension-meshi)
https://mclo.gs/0cmWb71

**Comment by FemBane** [comment]
I REALLY like this mod, love the lil critters :3 so I wanna make sure it's not a me issue

**Comment by SammySemicolon** [comment]
Facing the same issue

**Comment by PssbleTrngle** [comment]
Should be fixed on 2.2.1
