### ISSUE TITLE
Crash when pistons activated

### ISSUE THREAD

**Issue by n0tbad1** [EterDelta/CrittersAndCompanions#87]
Ver 1.20.1
Fabric 0.16.5
Critters And Companions [Fabric] 2.2.1 for 1.20.1

https://mclo.gs/BOokY5F

**Comment by PssbleTrngle** [comment]
fixed in dev, will be included in the next hotfix very soon

**Comment by PssbleTrngle** [comment]
Should be fixed in `2.2.2`
