### ISSUE TITLE
Incompatibility with Doggy Talents Next (1.20.1)

### ISSUE THREAD

**Issue by Cyther-Wuz-Taken** [EterDelta/CrittersAndCompanions#88]
Just recently made a small modded server for me and my friends. One of my friends turned his dog into a doggy talents dog and when he tried to open the doggy talents traits menu it doesn't open. 

Joined the doggy talents official discord and saw a message from the creator like from 4 days ago that they found an issue with critters and companions and that critters and companions is overwriting the menu somehow.

Idk if the doggy talents team is working on a a fix for it or not but figured it might be good for you guys to at least know.

**Comment by PssbleTrngle** [comment]
Should be causes by the same bug as #85, will be fixed in the next release of c&c very soon

**Comment by PssbleTrngle** [comment]
Should be fixed in `2.2.2`, if the issue still exists, feel free to re-open this
